library(tidyverse)
install.packages("tidyverse")
install.packages("ggplot")
library(ggplot2)
library(cluster)
library(factoextra)
install.packages("factoextra")
data("USArrests")
head(USArrests)
df <- scale(USArrests)
df
df <- na.omit(df)
head(df)
df <- scale(df)
head(df)
str(df)
kmeans_2 <- kmeans(df,centers = 10,nstart = 25)
kmeans_2
fviz_cluster(kmeans_2,data = df)

kmeans3 <- kmeans(df, centers = 3, nstart = 25)
kmeans4 <- kmeans(df, centers = 4, nstart = 25)  
kmeans5 <- kmeans(df, centers = 5, nstart = 25)  

plot1 <- fviz_cluster(kmeans_2, geom = "point", data = df) + ggtitle("k = 2")
plot2 <- fviz_cluster(kmeans3, geom = "point", data = df) + ggtitle("k = 3")
plot3 <- fviz_cluster(kmeans4, geom = "point", data = df) + ggtitle("k = 4")
plot4 <- fviz_cluster(kmeans5, geom = "point", data = df) + ggtitle("k = 5")
grid.arrange(plot1, plot2, plot3, plot4, nrow = 2)
library(gridExtra)
